# AML Splunk Core lab setup playbook   
#

- hosts: localhost
  connection: local
  become: true
  become_user: splunk

  tasks:
    - set_fact: SPLUNK_HOME="/opt/splunk"
      when: SPLUNK_HOME is undefined

    - name: check splunk install
      stat: 
        path: "{{ SPLUNK_HOME }}/etc/auth/server.pem"
        register: splunk_install
        failed_when: splunk_install not defined OR not splunk_install.isreg 

    - name: clone repos
      git:
        repo: 'https://github.com/rnewbold-splunk/techsummit22.git'
        dest: '~/ts22'
        clone: yes
        update: yes

    - name: update splunk profile
      blockinfile:
        dest: "~/.bashrc"
        block: |
          export PATH="{{ SPLUNK_HOME }}/bin:$PATH"
        marker: '# {mark} ANSIBLE MANAGED BLOCK'
        insertafter: EOF
        create: yes

    - name: create SLO certs
      block:
        - name: execute setup
          command: "~/ts22/splunkcore/files/splunk_boot_strap.sh setup"
          register: setup_status

        - name: check SLO certificate
          stat:
            path: "{{ SPLUNK_HOME }}/etc/auth/slocert/SLOcert.pem"
          register: slocert
          failed_when: slocert.stat.mode != '0700'
          when: setup_status is succeeded

    - name: install DataGen
      unarchive:
         src: "~/ts22/splunkcore/datagen/datapet.zip"
         dest: "{{ SPLUNK_HOME }}/etc/apps/"
         group: splunk
         owner: splunk
         mode: '750'
         remote_src: yes

    - name: restart splunkd service post config
      become: yes
      become_user: root
      systemd:
        name: Splunkd
        state: restarted
      failed_when: splunkdsvc.status['Result'] != 'success'
      ignore_errors: yes
      register: splunkdsvc

    - name: check data generators block
      block:
        - name: wait for splunkd to initialize
          wait_for:
            host: localhost
            port: 8088
            delay: 20
            sleep: 5
            timeout: 120

        - name: check data generators
          command: pgrep -f -a 'simdata|data-blaster'
          register: datagen_status 
          failed_when: datagen_status.stdout_lines|length < 1
          until: datagen_status is not failed
          retries: 10
          delay: 2
      when: splunkdsvc is succeeded

