# AML ITSI lab setup playbook   
#

- hosts: localhost
  connection: local

  tasks:
    - name: wait for splunk install
      wait_for:
        host: localhost
        port: 8089
        delay: 20
        sleep: 2
        timeout: 240

    - set_fact: SPLUNK_HOME="/opt/splunk"
      when: SPLUNK_HOME is undefined

    - name: clone repos
      become: true
      become_user: splunk
      git:
        repo: 'https://github.com/rnewbold-splunk/techsummit22.git'
        dest: '~/ts22'
        clone: yes
        update: yes

    - name: update splunk profile
      blockinfile:
        dest: ~/.bashrc
        block: |
          export PATH="{{ SPLUNK_HOME }}/bin:$PATH"
        marker: '# {mark} ANSIBLE MANAGED BLOCK'
        insertafter: EOF
        create: yes

    - name: create SLO certs
      become: true
      become_user: splunk
      block:

        - name: execute setup
          script: "~/ts22/splunkcore/files/splunk_boot_strap.sh setup"
          register: setup_status

        - name: check SLO certificate
          stat:
            path: "{{ SPLUNK_HOME }}/etc/auth/slocert/SLOcert.pem"
          register: slocert
          failed_when: slocert.stat.mode != '0700'
          when: setup_status is succeeded

    - name: install DataGen
      unarchive:
         src: "~/ts22/splunkcore/datagen/datapet.tgz"
         dest: "{{ SPLUNK_HOME }}/etc/apps/"

    - name: restart splunkd service post config
      become: yes
      systemd:
        name: Splunkd
        state: restarted
      failed_when: splunkdsvc.status['Result'] != 'success'
      ignore_errors: yes
      register: splunkdsvc

    - name: check data generators block
      block:
        - name: wait for splunkd to initialize
          wait_for:
            host: localhost
            port: 8088
            delay: 20
            sleep: 5
            timeout: 120

        - name: check data generators
          command: pgrep -f -a 'simdata|data-blaster'
          register: datagen_status 
          failed_when: datagen_status.stdout_lines|length < 1
          until: datagen_status is not failed
          retries: 10
          delay: 2
      when: splunkdsvc is succeeded

